name: amigo_doctor
description: Amigo Doctor
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  get: ^4.6.5
  reactive_forms: ^14.3.0
  http: ^0.13.5
  flutter_secure_storage: ^9.0.0
  google_fonts: ^4.0.4
  basic_utils: ^5.5.4
  font_awesome_flutter: ^10.4.0
  darq: ^1.2.1
  mobile_scanner: ^3.4.1
  loading_animation_widget: ^1.2.0+4
  permission_handler: ^11.0.1
  crypto: ^3.0.3
  flutter_advanced_drawer: ^1.3.5
  curved_navigation_bar: ^1.0.3
  flutter_form_builder: ^9.1.1
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/